version: "2.1"

services:

  web:
    tty: true
    image: python:3.8
    depends_on:
      - db
    volumes:
      - .:/opt/find-yourself
    container_name: find-yourself-web
    ports:
      - "0.0.0.0:8070:8000"
    env_file: .env
    working_dir: /opt/find-yourself
    command: /bin/bash -c 'scripts/run_server.sh'
    # command: tail -f /dev/null

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: find-yourself-db
    env_file: .env

volumes:
  postgres_data:
